- name: 김동주
  github_username: hepheir
  boj_username: hepheir

- name: 이윤호
  github_username: leeyh1011
  boj_username: leeyh1011

- name: 이은지
  github_username: Eunji1217
  boj_username: eunji1217

- name: 박민수
  github_username: pmsu2007
  boj_username: pmsu2008

- name: 손성빈
  github_username: SonSBiN
  boj_username: victorboy

- name: 박상우
  github_username: pswoo0323
  boj_username: pswoo0323

- name: 정지원
  github_username: jiwonsudo
  boj_username: jiwon50

- name: 조예빈
  github_username: Jyebin
  boj_username: yebin0322