name: Auto Assign
run-name: Auto assigning people to ${{ github.actor }}'s Pull Request. 🚀
on:
    pull_request_target:
        types:
            - opened
            - edited
            - reopened
            - ready_for_review
            - unlocked
jobs:
    Add-Reviewers:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: kentaro-m/auto-assign-action@v1.2.5
              name: Add reviewers to PR
              with:
                  configuration-path: ".github/auto_assign.yml"
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
